blog/urls.py
from django.conf.urls import url,include
from blog.views import *

app_name = 'blog'

urlpatterns = [
	# Example : /
	url(r'^$', PostLV.as_view(), name = 'index'),

	# Example : /post/ (same as /)
	url(r'^post/$', PostLV.as_view(), name = 'post_list'),

	# Example : /post/django-example/
	url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name = 'post_detail'),

	# Example : /archive/
	url(r'^archive/$', PostAV.as_view(), name = 'post_archive'),

	# Example : /2012/
	url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name = 'post_year_archive'),

	# Example : /2012/nov/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name = 'post_month_archive'),

	# Example : /2012/nov/10/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name = 'post_day_archive'),

	# Example : /today/
	url(r'^today/$', PostTAV.as_view(), name = 'post_today_archive'),

	# Example: /tag/
	url(r'^tag/$', TagTV.as_view(), name = 'tag_cloud'),

	# Example: /tag/tagname/
	url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

	# Example: /search/
	url(r'^search/$', SearchFormView.as_view(), name='search'),

	#### add below for edit
	# Example: /add/
	url(r'^add/$', PostCreateView.as_view(), name="add"),

	# Example: /change/
	url(r'^change/$', PostChangeLV.as_view(), name="change"),

	# Example: /99/update/
	url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name="update"),

	# Example: /99/delete/
	url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name="delete"),

	url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor
]

bookmark/urls.py
from django.conf.urls import url
#from bookmark.views import BookmarkLV, BookmarkDV
from bookmark.views import * # for edit

app_name = 'bookmark'

urlpatterns= [
	#Class-based views
	url(r'^$', BookmarkLV.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),

	#### add below for edit
	# Example: /add/
	url(r'^add/$', BookmarkCreateView.as_view(), name="add"),

	# Example: /change/
	url(r'^change/$', BookmarkChangeLV.as_view(), name="change"),

	# Example: /99/update/
	url(r'^(?P<pk>[0-9]+)/update/$', BookmarkUpdateView.as_view(), name="update"),

	# Example: /99/delete/
	url(r'^(?P<pk>[0-9]+)/delete/$', BookmarkDeleteView.as_view(), name="delete"),

	#chart
    #url(r'^$', BookmarkLV.main_page),
    url(r'^data.json$', BookmarkLV.data_json),

    url(r'^visiters$', BookmarkDV.hit_count),

]

myweb/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
#from home import views
from django.conf.urls.static import static  # add for photo
from django.conf import settings  # add for photo
from myweb.views import HomeView, HomeMobiView, UserCreateView, UserCreateDoneTV # for auth
import practice.views
#from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     # auth URL 3
#     url(r'^accounts/', include('django.contrib.auth.urls')),
#     url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
#     url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

#     url(r'^$', HomeView.as_view(), name='home'), 
#     url(r'^bookmark/', include('bookmark.urls', )),
#     url(r'^blog/', include('blog.urls', )),
# #    url(r'^$', views.index),
#     url(r'^photo/', include('photo.urls', )), # add for photo

#     # url(r'^rss/', include('rss.urls', )), # add for rss
# 	# Class-based view for bookmark app
# 	#url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
# 	#url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail')
#     url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor

#     # mobile
#     url(r'^m/', HomeMobiView.as_view(), name='mobihome'),

#     #practice
#     url(r'^practice/', include('practice.urls', )),

#     url(r'^bit.json$', HomeView.bitsise),    

    url(r'^admin/', admin.site.urls),
    # auth URL 3
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'), 
    path(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    path(r'^blog/', include('blog.urls', namespace='blog' )),
#    url(r'^$', views.index),
    path(r'^photo/', include('photo.urls', namespace='photo')), # add for photo

    # url(r'^rss/', include('rss.urls', )), # add for rss
    # Class-based view for bookmark app
    #url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
    #url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail')
    url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor

    # mobile
    url(r'^m/', HomeMobiView.as_view(), name='mobihome'),

    #practice
    url(r'^practice/', include('practice.urls', )),

    url(r'^bit.json$', HomeView.bitsise), 
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # add for photo

bookmark/models.py
from __future__ import unicode_literals #python 2.x support

from django.db import models
# from django.utils.encoding import python_2_unicode_compatible
from six import python_2_unicode_compatible
from django.contrib.auth.models import User # for edit

# Create your models here.

@python_2_unicode_compatible
class Bookmark(models.Model):
	title = models.CharField(max_length=100, blank=True, null=True)
	url = models.URLField('url', unique=True)
	owner = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING,) # for edit
	visiters = models.IntegerField(blank=True, null=True, default=0)

	def __str__(self):
		return self.title

bookmark/views.py
from django.shortcuts import render, HttpResponse#, render_to_response #render_to_response는 render로 통합 

from django.views.generic import ListView, DetailView
#from django.views.generic.base import TemplateView
from bookmark.models import Bookmark

from django.views.generic.edit import CreateView, UpdateView, DeleteView # for edit
# from django.core.urlresolvers import reverse_lazy # for edit #outdated
from django.urls import reverse_lazy
from myweb.views import LoginRequiredMixin # for edit

# chart
import random, json
import pandas as pd
# from vincent.colors import brews
from django.db.models import F
import sys

# Create your views here.

#---ListView
class BookmarkLV(ListView):
	model = Bookmark
	def data_json(request):
	    Counts = ['접속자수', ]
	    Costs = ['접속횟수',]
	    # for f in BookmarkLV.model.objects.all():
	    # 	Counts.append(f.title)
	    # 	Costs.append(f.visiters)
	    # data = {
	    #     'columns': [
	    #         Counts,
	    #         Costs,
	    #     ]
	    # }
	    
	    series = []

	    
	    for f in BookmarkLV.model.objects.all():
	    	temp = {}
	    	temp_list =[]
	    	temp['name'] = f.title
	    	temp_list.append(f.visiters)
	    	temp['data'] = temp_list
	    	series.append(temp)

	    
	    print(json.dumps(series))

	    return HttpResponse(json.dumps(series),content_type='text/json')
	def main_page(request):
		# return render_to_response('bookmark_list.html')
		return render(None, 'bookmark_list.html')

	

#---DetailView
class BookmarkDV(DetailView):
	model = Bookmark	
	def hit_count(request):
		h_id = request.GET.get("id","")
		mymodel = BookmarkDV.model.objects.filter(id__in=h_id).update(visiters=F('visiters')+1)		
		data = { 'id': [ h_id] }
		return HttpResponse(json.dumps(data),content_type='text/json')
		

# add below for edit 
class BookmarkCreateView(LoginRequiredMixin, CreateView):
	model = Bookmark
	fields = ['title', 'url', 'visiters']
	success_url = reverse_lazy('bookmark:index')

	def form_valid(self, form):
		form.instance.owner = self.request.user
		return super(BookmarkCreateView, self).form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
	template_name = 'bookmark/bookmark_change_list.html'

	def get_queryset(self):
		return Bookmark.objects.filter(owner = self.request.user)

class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
	model = Bookmark
	fields = ['title', 'url']
	success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(LoginRequiredMixin, DeleteView):
	model = Bookmark
	success_url = reverse_lazy('bookmark:index')


bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}bookmark_change_list.html{% endblock %}

{% block content %}
	<div id="content">
		<h1>즐겨찾기 변경 - {{ user }}</h1>

		<table class="change-list">
			<tr>
				<th>Title</th>
				<th>Url</th>
				<th>Owner</th>
				<th>Update</th>
				<th>Delete</th>
			</tr>
			{% for item in object_list %}
			<tr>
				<td>{{ item.title}}</td>
				<td>{{ item.url}}</td>
				<td>{{ item.owner}}</td>
				<td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
				<td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
			</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}
	<div id="content">
		<h1>즐겨찾기 삭제</h1>

		<form action="." id="submitrow" method="post">{% csrf_token %}
			<p>"{{ object }}" 즐겨찾기를 삭제 하시겠습니까? </p>
			<input type="submit" value="Confirm" />
		</form>
	</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %} BookMark Detail {% endblock %}

{% block content %}
<script type="text/javascript">
	function fn_increase(id){
	$.get('/bookmark/visiters', { 'id': '{{object.id}}'
		                           /*,'csrfmiddlewaretoken': token*/
		                         }, 
									function(data, status){
										if(data.status == 'error'){
											alert('hitcount error');
										}
									},
									'json'
	      );

	}


</script>
	<div id="content">
		<h1>{{ object.title}}</h1>

		<ul>
			<li>URL: <a href="{{object.url}}" target="_blank" onclick="fn_increase('{{object.id}}')">{{ object.url }} </a></li>
		</ul>
	</div>
	<form id="hitcount" action="/bookmark/visiters" method="post"> {% csrf_token %}
		<input type="hidden" name="id" value="{{object.id}}" />				
	</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}

{% block title %}bookmark_form.html{% endblock %}
{% load static %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}
{% block content %}
	<div id="content">
		<h1>즐겨찾기 추가 - {{user}}</h1>

		<form action="." id="submitrow" method="post">{% csrf_token %}

			{% if form.errors %}
			<p class="errornote">Wrong! Please correct the error(s) below.</p>
			{% endif %}

			<p>즐겨찾기를 추가 합니다.</p>

			<fieldset class="aligned">
				
				<div class="form-row">
					{{ form.title.label_tag }} {{ form.title }}
				</div>
				<div class="form-row">
					{{ form.url.label_tag }} {{ form.url }}
				</div>

				<input type="hidden" name="visiters" value="0" />				
				
			</fieldset>
			
			<div class="fl_right">	
				<div class="content-container" onclick="fn_submit();"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">제출</h3></fieldset></div> <!-- write -->	
			</div>

			<script type="text/javascript">document.getElementById('id_title').focus();</script>
			
		</form>

	</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %} BookMark List {% endblock %}

{% block content %}
<div id="content">
	<h1>즐겨찾기 목록</h1>
	
	<div class="bookmark-list">
		{% for bookmark in object_list %}
		<ul>
			<li>
			<div class="cont_post">
				<h2><a href="{% url 'bookmark:detail' bookmark.id %}" class="txt_wrap">{{bookmark}}</a></h2>			
			</div>
			</li>
		</ul>
		{% endfor %}
		<hr style="margin: 5px 0;">
		<div class="fl_right">	
			<div class="content-container" onclick="fn_write();"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">즐겨찾기 추가</h3></fieldset></div> <!-- write -->
		</div>
	</div>

	<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto">
		<script type="text/javascript">
	        $.get('/bookmark/data.json', function(jsondata) {
	            Highcharts.chart('container', {
	               chart: {
	                    type: 'column'	                    
	                },
	                title: {
	                	text: ''
	                },
					yAxis: {
				        min: 0,
				        title: {
				            text: 'hits'
				        }
				    },
				    xAxis:{
				    	categories:['접속횟수'],
				    	crosshair: true
				    },
	                series: jsondata
	            });
	        });
	    </script>
	</div>

</div>	
{% endblock %}