blog/urls.py
from django.conf.urls import url,include
from blog.views import *

app_name = 'blog'

urlpatterns = [
	# Example : /
	url(r'^$', PostLV.as_view(), name = 'index'),

	# Example : /post/ (same as /)
	url(r'^post/$', PostLV.as_view(), name = 'post_list'),

	# Example : /post/django-example/
	url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name = 'post_detail'),

	# Example : /archive/
	url(r'^archive/$', PostAV.as_view(), name = 'post_archive'),

	# Example : /2012/
	url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name = 'post_year_archive'),

	# Example : /2012/nov/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name = 'post_month_archive'),

	# Example : /2012/nov/10/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name = 'post_day_archive'),

	# Example : /today/
	url(r'^today/$', PostTAV.as_view(), name = 'post_today_archive'),

	# Example: /tag/
	url(r'^tag/$', TagTV.as_view(), name = 'tag_cloud'),

	# Example: /tag/tagname/
	url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

	# Example: /search/
	url(r'^search/$', SearchFormView.as_view(), name='search'),

	#### add below for edit
	# Example: /add/
	url(r'^add/$', PostCreateView.as_view(), name="add"),

	# Example: /change/
	url(r'^change/$', PostChangeLV.as_view(), name="change"),

	# Example: /99/update/
	url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name="update"),

	# Example: /99/delete/
	url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name="delete"),

	url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor
]

myweb/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
#from home import views
from django.conf.urls.static import static  # add for photo
from django.conf import settings  # add for photo
from myweb.views import HomeView, HomeMobiView, UserCreateView, UserCreateDoneTV # for auth
import practice.views
#from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     # auth URL 3
#     url(r'^accounts/', include('django.contrib.auth.urls')),
#     url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
#     url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

#     url(r'^$', HomeView.as_view(), name='home'), 
#     url(r'^bookmark/', include('bookmark.urls', )),
#     url(r'^blog/', include('blog.urls', )),
# #    url(r'^$', views.index),
#     url(r'^photo/', include('photo.urls', )), # add for photo

#     # url(r'^rss/', include('rss.urls', )), # add for rss
# 	# Class-based view for bookmark app
# 	#url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
# 	#url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail')
#     url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor

#     # mobile
#     url(r'^m/', HomeMobiView.as_view(), name='mobihome'),

#     #practice
#     url(r'^practice/', include('practice.urls', )),

#     url(r'^bit.json$', HomeView.bitsise),    

    url(r'^admin/', admin.site.urls),
    # auth URL 3
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'), 
    path(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    path(r'^blog/', include('blog.urls', namespace='blog' )),
#    url(r'^$', views.index),
    path(r'^photo/', include('photo.urls', namespace='photo')), # add for photo

    # url(r'^rss/', include('rss.urls', )), # add for rss
    # Class-based view for bookmark app
    #url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
    #url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail')
    url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor

    # mobile
    url(r'^m/', HomeMobiView.as_view(), name='mobihome'),

    #practice
    url(r'^practice/', include('practice.urls', )),

    url(r'^bit.json$', HomeView.bitsise), 
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # add for photo

blog/models.py
from __future__ import unicode_literals
# from django.utils.encoding import python_2_unicode_compatible #outdated
from six import python_2_unicode_compatible

from django.db import models
from django.contrib import admin
from django import forms
# from django.core.urlresolvers import reverse #outdated
from django.urls import reverse
from tagging.fields import TagField # tagging
from django.contrib.auth.models import User # for edit
from django.utils.text import slugify # for edit
#from ckeditor_widget.widgets import CKEditorWidget
from ckeditor.fields import RichTextField,RichTextFormField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.
@python_2_unicode_compatible
class Post(models.Model):
	title = models.CharField('TITLE', max_length=50)
	slug = models.SlugField('SLUG', unique=True, allow_unicode = True, help_text='one word for title alias')
	description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
	#content = models.TextField('CONTENT')
	content = RichTextUploadingField()
	create_date = models.DateTimeField('Create Date', auto_now_add=True)
	modify_date = models.DateTimeField('Modify Date', auto_now=True)
	tag = TagField() # tagging
	owner = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING,) # for edit

	class Meta:
		verbose_name='post'
		verbose_name_plural='posts'
		db_table = 'my_post'
		ordering = ('-modify_date',)

	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse('blog:post_detail', args = (self.slug,))

	def get_previous_post(self):
		return self.get_previous_by_modify_date()

	def get_next_post(self):
		return self.get_next_by_modify_date()

	#for edit
	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.title, allow_unicode=True)
		super(Post, self).save(*args, **kwargs)


blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView,TemplateView #TemplateView add
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from blog.models import Post
from tagging.models import Tag, TaggedItem # add
from tagging.views import TaggedObjectList # add

##----- search
from django.views.generic.edit import FormView # add class type generic view
from blog.forms import PostSearchForm # add Search Form which defined forms.py
from django.db.models import Q # add class Q for search
from django.shortcuts import render # add shortcut function

##------edit
from django.views.generic.edit import CreateView, UpdateView, DeleteView # for edit
# from django.core.urlresolvers import reverse_lazy # for edit #outdated
from django.urls import reverse_lazy
from myweb.views import LoginRequiredMixin # for edit

# Create your views here.

#----TemplateView
class TagTV(TemplateView):
	template_name = 'tagging/tagging_cloud.html'

#----ListView
class PostLV(ListView):
	model=Post
	template_name = 'blog/post_all.html'
	context_object_name = 'posts'
	paginate_by = 10

class PostTOL(TaggedObjectList):
	model = Post
	template_name = 'tagging/tagging_post_list.html'

#----DetailView
class PostDV(DetailView):
	model = Post	

#-----ArchiveView
class PostAV(ArchiveIndexView):
	model = Post
	date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field='modify_date'
    make_object_list=True

class PostMAV(MonthArchiveView):
	model = Post
	date_field = 'modify_date'

class PostDAV(DayArchiveView):
	model = Post
	date_field = 'modify_date'

class PostTAV(TodayArchiveView):
	model = Post
	date_field = 'modify_date'

#---- Form View
class SearchFormView(FormView):
	form_class = PostSearchForm
	template_name = 'blog/post_search.html'

	def form_valid(self, form):
		schWord = '%s' % self.request.POST['search_word']
		post_list = Post.objects.filter(Q(title__icontains=schWord) | Q(description__icontains=schWord) | Q(content__icontains=schWord)).distinct()

		context = {}
		context['form'] =  form
		context['search_term'] = schWord
		context['object_list'] = post_list

		return render(self.request, self.template_name, context) # No Reirection

#------edit
class PostCreateView(LoginRequiredMixin, CreateView):
	model = Post
	fields = ['title', 'slug', 'description', 'content','tag']
	initial = {'slug': 'auto-filling-do-not-input' }
	#fields = ['title', 'description', 'content','tag']
	success_url = reverse_lazy('blog:index')

	def form_valid(self, form):
		form.instance.owner = self.request.user
		return super(PostCreateView, self).form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
	template_name = 'blog/post_change_list.html'

	def get_queryset(self):
		return Post.objects.filter(owner = self.request.user)

class PostUpdateView(LoginRequiredMixin, UpdateView):
	model = Post
	fields = ['title', 'slug', 'description', 'content','tag']
	success_url = reverse_lazy('blog:index')

class PostDeleteView(LoginRequiredMixin, DeleteView):
	model = Post
	success_url = reverse_lazy('blog:index')


blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %} Blog List {% endblock %}

{% load static %}
{% block extrastyle %}{% static "tagging/tag.css" %}{% endblock %}

{% block content %}
<div class="blog-list" id="blog-list">
	{% for post in posts %}
		<div class="cont_post" id="post{{ post.id }}">
			<h2><a href='{{ post.get_absolute_url }}' class="txt_wrap">{{post.title}}</a></h2>
			<div id="cont_img" class="cont_img">				
				<a href="{{ post.get_absolute_url }}"><img id="img{{ post.id }}" src="" style="width: 100%; height: auto;" /></a>
			</div>
			<div id="{{ post.id }}" class="">{{ post.content }}</div>								
			{{post.modify_date|date:"N d, Y"}}
		</div>
		<script type="text/javascript">
			/**리스트에 img thumbnail 넣기 */
			var s =	$("#{{ post.id }}").html();			
			var e = document.createElement('div');
			e.innerHTML = s;
			var htm = e.childNodes[0].nodeValue;
			e.innerHTML = htm;
			if(!(/Mobi/.test(navigator.userAgent))){
				var str = e.getElementsByTagName("img")[0];
				if( e.getElementsByTagName("img")[0] != "undefined" && e.getElementsByTagName("img")[0] != undefined ){
					var src = e.getElementsByTagName("img")[0].outerHTML;
					var tgt = document.getElementById("img{{ post.id }}");
					tgt.src = e.getElementsByTagName("img")[0].src;
					
				}
			}else{
				$("#cont_img").remove();
				$("#post{{ post.id }}").css("width", "100%");
				$("#blog-list").css("width", "80%");
			}
			/**리스트에서 img 태그 제거 */
			/*var txt = $("#{{ post.id }}").text();
			$("#{{ post.id }}").text('').append(txt).find('img').remove().end().text();*/
			var xxx = $(htm).text();
			$('#{{post.id}}').text(xxx);
		</script>
	{% endfor %}

	<div style="height: 10px;"></div>

	<div style="text-align: center;font-size: 22px;">
			<span>
			{% if page_obj.has_previous  %}
				<a href="?page={{ page_obj.previous_page_number }}">◀</a>
			{% endif  %}

			{% if page_obj.has_previous or page_obj.has_next  %}
			{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
			{% endif %}

			{% if page_obj.has_next  %}
				<a href="?page={{ page_obj.next_page_number }}">▶</a>
			{% endif   %}
			</span>
		</div>
	<hr style="margin: 5px 0;">
	<div class="fl_right">	
		<div class="content-container" onclick="fn_write();"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">글쓰기</h3></fieldset></div> <!-- write -->	
	</div>
</div>

{% endblock %}

blog/templates/blog/post_archive.html
<h1>Post Arvhives until {% now "N d, Y" %} </h1>
<ul>
	{% for date in date_list %}
	<li style="display:inline;">
		<a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y"}}</a>
	</li>
	{% endfor %}
</ul>

<div style="height: 10px;"></div>

<div>
	<ul>
		{% for post in object_list %}
		<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
		<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
		</li>
		{% endfor %}
	</ul>	
</div>

blog/templates/blog/post_archive_day.html
<h1>Post Arvhives for {% day|date:"N d, Y" %} </h1>


<div>
	<ul>
		{% for post in object_list %}
		<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
		<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
		</li>
		{% endfor %}
	</ul>	
</div>

blog/templates/blog/post_archive_month.html
<h1>Post Arvhives for {% month|date:"N, Y" %} </h1>


<div>
	<ul>
		{% for post in object_list %}
		<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
		<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
		</li>
		{% endfor %}
	</ul>	
</div>

blog/templates/blog/post_archive_year.html
<h1>Post Arvhives for {% year|date:"Y" %} </h1>
<ul>
	{% for date in date_list %}
	<li style="display:inline;">
		<a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F"}}</a>
	</li>
	{% endfor %}
</ul>

<div style="height: 10px;"></div>

<div>
	<ul>
		{% for post in object_list %}
		<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
		<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
		</li>
		{% endfor %}
	</ul>	
</div>

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}
	<div id="content">
		<h1>Post Delete</h1>

		<form action="." id="submitrow" method="post">{% csrf_token %}
			<p>정말로 포스트를 삭제하시겠습니까 - "{{ object }}" ? </p>
			<div class="fl_left">	
				<div class="content-container" onclick="fn_submit();"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">삭제</h3></fieldset></div> <!-- write -->	
			</div>
		</form>
	</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %} post_detail.html {% endblock %}

{% load static %}
{% block extrastyle %}{% static "tagging/tag.css" %}{% endblock %}

{% block content %}
<script type="text/javascript">
	function fn_move(todo, itemId){
		document.location.href="../../" + itemId + "/" + todo;
	}

</script>
<div id="content">
	<h2 class="post_title">{{ object.title }}</h2>
	

	<div class="container">	
		<p class="date"> {{object.modify_date|date:"N d, Y"}}</p>

		<div style="height: 10px;"></div>

		<div class="body" id="cont1">
			{{ object.content}}
		</div>
		<script type="text/javascript">
			var s= document.getElementById("cont1").innerHTML;
			var e = document.createElement('div');
  			e.innerHTML = s;
  			var htm = e.childNodes[0].nodeValue;
  			document.getElementById("cont1").innerHTML = htm;
		</script>
		<div>
			<b>TAGS: </b>
			{% load tagging_tags %}
			{% tags_for_object object as tags %}
			{% for tag in tags %}
			<a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
			{% endfor %}
			<a href="{% url 'blog:tag_cloud' %}"><i>[ TagCloud ]</i></a>
		</div>

		<div class="gap10"></div>
		<div>
		{% load disqus_tags %}
		{% disqus_show_comments %}
		</div>
	</div>

	<hr style="margin: 5px 0;">
	<div class="fl_right">	
		<div class="content-container" style="position: relative;" onclick="fn_move('delete', {{object.id }});"><fieldset><h3 style="text-align:center;color:rgba(252,10,50,1);">삭제</h3></fieldset></div> 
	</div>
	<div class="fl_right">	
		<div class="content-container" style="position: relative;" onclick="fn_move('update', {{object.id }});"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">편집</h3></fieldset></div> 
	</div>
	
	<p class="fl_left">
	{% if object.get_previous_by_modify_date %}
		이전글: <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post">{{ object.get_previous_post}} </a>
	{% endif %}
	</p>

	<p class="fl_right">
	{% if object.get_next_by_modify_date %}
		다음글: <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">{{ object.get_next_post}} </a>
	{% endif %}
	</p>
</div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends "base.html" %}

{% block title %}post_form.html{% endblock %}
{% load static %}

{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block extrahead %}<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>{{ block.super }}{% endblock %}

{% block content %}
	<div id="content">
		<h1>Post 등록/편집 - {{user}}</h1>

		<form action="." method="post" id="submitrow">{% csrf_token %}

			{% if form.errors %}
			<p class="errornote">Wrong! Please correct the error(s) below.</p>
			{% endif %}

			<p>포스트를 등록 또는 편집 합니다.</p>

			<fieldset class="aligned">
				
				<div class="form-row">
					{{ form.title.label_tag }} {{ form.title }}
				</div>
				<div class="form-row">
					{{ form.slug.label_tag }} {{ form.slug }}
				</div>
				<div class="form-row">
					{{ form.description.label_tag }} {{ form.description }}
				</div>
				<div class="form-row">
					{{ form.content.label_tag }} {{ form.content }}
				</div>
				<div class="form-row">
					{{ form.tag.label_tag }} {{ form.tag }}
				</div>
			</fieldset>

			<div class="fl_right">	
				<div class="content-container" onclick="fn_submit();"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">제출</h3></fieldset></div> <!-- write -->	
			</div>

			<script type="text/javascript">document.getElementById('id_title').focus();</script>
			
		</form>

	</div>
{% endblock %}