blog/urls.py
from django.conf.urls import url,include
from blog.views import *

app_name = 'blog'

urlpatterns = [
	# Example : /
	url(r'^$', PostLV.as_view(), name = 'index'),

	# Example : /post/ (same as /)
	url(r'^post/$', PostLV.as_view(), name = 'post_list'),

	# Example : /post/django-example/
	url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name = 'post_detail'),

	# Example : /archive/
	url(r'^archive/$', PostAV.as_view(), name = 'post_archive'),

	# Example : /2012/
	url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name = 'post_year_archive'),

	# Example : /2012/nov/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name = 'post_month_archive'),

	# Example : /2012/nov/10/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name = 'post_day_archive'),

	# Example : /today/
	url(r'^today/$', PostTAV.as_view(), name = 'post_today_archive'),

	# Example: /tag/
	url(r'^tag/$', TagTV.as_view(), name = 'tag_cloud'),

	# Example: /tag/tagname/
	url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

	# Example: /search/
	url(r'^search/$', SearchFormView.as_view(), name='search'),

	#### add below for edit
	# Example: /add/
	url(r'^add/$', PostCreateView.as_view(), name="add"),

	# Example: /change/
	url(r'^change/$', PostChangeLV.as_view(), name="change"),

	# Example: /99/update/
	url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name="update"),

	# Example: /99/delete/
	url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name="delete"),

	url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor
]

myweb/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
#from home import views
from django.conf.urls.static import static  # add for photo
from django.conf import settings  # add for photo
from myweb.views import HomeView, HomeMobiView, UserCreateView, UserCreateDoneTV # for auth
import practice.views
#from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     # auth URL 3
#     url(r'^accounts/', include('django.contrib.auth.urls')),
#     url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
#     url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

#     url(r'^$', HomeView.as_view(), name='home'), 
#     url(r'^bookmark/', include('bookmark.urls', )),
#     url(r'^blog/', include('blog.urls', )),
# #    url(r'^$', views.index),
#     url(r'^photo/', include('photo.urls', )), # add for photo

#     # url(r'^rss/', include('rss.urls', )), # add for rss
# 	# Class-based view for bookmark app
# 	#url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
# 	#url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail')
#     url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor

#     # mobile
#     url(r'^m/', HomeMobiView.as_view(), name='mobihome'),

#     #practice
#     url(r'^practice/', include('practice.urls', )),

#     url(r'^bit.json$', HomeView.bitsise),    

    url(r'^admin/', admin.site.urls),
    # auth URL 3
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'), 
    path(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    path(r'^blog/', include('blog.urls', namespace='blog' )),
#    url(r'^$', views.index),
    path(r'^photo/', include('photo.urls', namespace='photo')), # add for photo

    # url(r'^rss/', include('rss.urls', )), # add for rss
    # Class-based view for bookmark app
    #url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
    #url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail')
    url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor

    # mobile
    url(r'^m/', HomeMobiView.as_view(), name='mobihome'),

    #practice
    url(r'^practice/', include('practice.urls', )),

    url(r'^bit.json$', HomeView.bitsise), 
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # add for photo

photo/urls.py
from django.conf.urls import url
from photo.views import *

app_name = 'photo'

urlpatterns = [
	# Example : /
	url(r'^$', AlbumLV.as_view(), name = 'index'),

	# Example : /album/, same as /
	url(r'^album/$', AlbumLV.as_view(), name = 'album_list'),

	# Example : /album/99
	url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name = 'album_detail'),

	# Example : /photo/99
	url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name = 'photo_detail'),

	# Example : /album/add/
	url(r'^album/add/$' , AlbumPhotoCV.as_view(), name="album_add"),

	# Example : /album/change/
	url(r'^album/change/$' , AlbumChangeLV.as_view(), name="album_change"),

	# Example : /album/99/update/
	url(r'^album/(?P<pk>[0-9]+)/update/$' , AlbumPhotoUV.as_view(), name="album_update"),

	# Example : /album/99/delete/
	url(r'^album/(?P<pk>[0-9]+)/delete/$' , AlbumDeleteView.as_view(), name="album_delete"),

	# Example : /photo/add/
	url(r'^photo/add/$' , PhotoCreateView.as_view(), name="photo_add"),

	# Example : /photo/change/
	url(r'^photo/change/$' , PhotoChangeLV.as_view(), name="photo_change"),

	# Example : /photo/99/update/
	url(r'^photo/(?P<pk>[0-9]+)/update/$' , PhotoUpdateView.as_view(), name="photo_update"),

	# Example : /photo/99/delete/
	url(r'^photo/(?P<pk>[0-9]+)/delete/$' , PhotoDeleteView.as_view(), name="photo_delete"),


]

photo/models.py
from __future__ import unicode_literals
# from django.utils.encoding import python_2_unicode_compatible #outdated
from six import python_2_unicode_compatible

from django.db import models

# from django.core.urlresolvers import reverse #outdated
from django.urls import reverse
from photo.fields import ThumbnailImageField
from django.contrib.auth.models import User # for edit
# Create your models here.

@python_2_unicode_compatible
class Album(models.Model):
	name = models.CharField(max_length=50)
	description = models.CharField('One Line Description', max_length=100, blank=True)
	owner = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING,) # for edit

	class Meta:
		ordering = ['name']

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('photo:album_detail', args=(self.id,))

@python_2_unicode_compatible
class Photo(models.Model):
	album = models.ForeignKey(Album, on_delete=models.DO_NOTHING,)
	title = models.CharField(max_length=50)
	image = ThumbnailImageField(upload_to='photo/%Y/%m')
	description = models.TextField('Photo Description', blank=True)
	upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
	owner = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING,) # for edit
	
	class Meta:
		ordering = ['title']

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('photo:photo_detail', args=(self.id,))
			

photo/views.py
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo
#from django.shortcuts import render

#----add 3lines below for edit
from django.views.generic.edit import CreateView, UpdateView, DeleteView # for edit
# from django.core.urlresolvers import reverse_lazy # for edit #outdated
from django.urls import reverse_lazy
from myweb.views import LoginRequiredMixin # for edit

# Create your views here.
class AlbumLV(ListView):
	model = Album

class AlbumDV(DetailView):
	model = Album

class PhotoDV(DetailView):
	model = Photo

# ---- Add/Change/Update/Delete for Photo
class PhotoCreateView(LoginRequiredMixin, CreateView):
	model = Photo
	fields = ['album', 'title', 'image', 'description']
	success_url = reverse_lazy('photo:index')
	def form_valid(self, form):
		form.instance.owner = self.request.user
		return super(PhotoCreateView, self).form_valid(form)

class PhotoChangeLV(LoginRequiredMixin, ListView):
	#model = Photo
	template_name = 'photo/photo_change_list.html'

	def get_queryset(self):
		return Photo.objects.filter(owner=self.request.user)

class PhotoUpdateView(LoginRequiredMixin, UpdateView):
	model = Photo
	fields = ['album', 'title', 'image', 'description']
	success_url = reverse_lazy('photo:index')

class PhotoDeleteView(LoginRequiredMixin, DeleteView):
	model = Photo
	success_url = reverse_lazy('photo:index')	

#------ Add/chage/update/delete for Album
# ---- chage/delete for album
class AlbumChangeLV(LoginRequiredMixin, ListView):
	template_name = 'photo/album_change_list.html'

	def get_queryset(self):
		return Album.objects.filter(owner=self.request.user)

class AlbumDeleteView(LoginRequiredMixin, DeleteView):
	model = Album
	success_url = reverse_lazy('photo:index')	

# --- inlineFormset view
# --- add/update for album
from django.shortcuts import redirect
from photo.forms import PhotoInlineFormSet

class AlbumPhotoCV(LoginRequiredMixin, CreateView):
	model = Album
	fields = ['name', 'description']
	template_name = 'photo/album_form.html'

	def get_context_data(self, **kwargs):
		context = super(AlbumPhotoCV, self).get_context_data(**kwargs)
		if self.request.POST :
			context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
		else:
			context['formset'] = PhotoInlineFormSet()
		return context

	def form_valid(self, form):
		form.instance.owner = self.request.user
		context = self.get_context_data()
		formset = context['formset']
		for photoform in formset :
			photoform.instance.owner = self.request.user
		if formset.is_valid():
			self.object = form.save()
			formset.instance = self.object
			formset.save()
			return redirect(self.object.get_absolute_url())
		else:
			return self.render_to_response(self.get_context_data(form=form))

class AlbumPhotoUV(LoginRequiredMixin, UpdateView):
	model = Album
	fields = ['name', 'description' ]
	template_name = 'photo/album_form.html'

	def get_context_data(self, **kwargs):
		context = super(AlbumPhotoUV, self).get_context_data(**kwargs)
		if self.request.POST:
			context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
		else:
			context['formset'] = PhotoInlineFormSet(instance=self.object)
		return context

	def form_valid(self, form):
		context = self.get_context_data()
		formset = context['formset']
		if formset.is_valid():
			self.object = form.save()
			formset.instance = self.object
			formset.save()
			return redirect(self.object.get_absolute_url())
		else:
			return self.render_to_response(self.get_context_data(form=form))

photo/templates/photo/album_change_list.html
{% extends "base.html" %}

{% block title %}album_change_list.html{% endblock %}

{% block content %}
	<div id="content">
		<h1>앨범 변경 - {{ user }}</h1>

		<table class="change-list">
			<tr>
				<th>Name</th>
				<th>Description</th>
				<th>Owner</th>
				<th>Update</th>
				<th>Delete</th>
			</tr>

			{% for item in object_list %}
			<tr>
				<td>{{ item.name}}</td>
				<td>{{ item.description}}</td>
				<td>{{ item.owner}}</td>
				<td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
				<td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
			</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}

photo/templates/photo/album_confirm_delete.html
{% extends "base.html" %}

{% block title %}album_confirm_delete.html{% endblock %}

{% block content %}
	<div id="content">
		<h1>앨범 삭제</h1>

		<form action="." id="submitrow" method="post">{% csrf_token %}
			<p>다음 앨범을 정말로 삭제하겠습니까 - "{{ object }}" ? </p>
			<div class="fl_left">	
			<div class="content-container" onclick="fn_submit();"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">확인</h3></fieldset></div> <!-- write -->	
		</div>
		</form>
	</div>
{% endblock %}

photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}album_detail.html{% endblock %}

{% load static %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<script type="text/javascript">
	function fn_move(todo, itemId){
		document.location.href="../" + itemId + "/" + todo;
	}

</script>
<div id ="content">
	<div class="fl_right">	
		<div class="content-container" style="position: relative;" onclick="fn_move('delete', {{object.id }});"><fieldset><h3 style="text-align:center;color:rgba(252,10,50,1);">삭제</h3></fieldset></div> 
	</div>
	<div class="fl_right">	
		<div class="content-container" style="position: relative;" onclick="fn_move('update', {{object.id }});"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">편집</h3></fieldset></div> 
	</div>
	<div class="clear_float">
		<h2 style="display:inline;">{{ object.name}}</h2>
		&emsp;
		<b><i>{{ object.description }}</i></b>
	</div>

	<hr/>

	<div class="album-detail">
		{% for photo in object.photo_set.all %} <!--print 5 thumbnail -->
		<div class="album-detail-photo">
			<a href="{{ photo.get_absolute_url }}">
				<img class="thumbnail" src="{{ photo.image.thumb_url }}" />
			</a>
			<li>{{ photo.title}}</li>
			<li>{{ photo.upload_date|date:"Y-m-d" }}</li>
		</div>
		{% endfor %}
	</div>	
</div>
{% endblock %}

photo/templates/photo/album_form.html
{% extends "base.html" %}

{% block title %}album_form.html{% endblock %}

{% load static %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id ="content">
	<h1>앨범 등록/수정</h1>

	{% if form.is_multipart or formset.is_multipart %}
	<form enctype="multipart/form-data" id="submitrow" method="post" action=".">
	{% else %}
	<form method="post" id="submitrow" action=".">
	{% endif %}
		{% csrf_token %}

		{% if form.errors %}
			<p class="errornote">Wrong! Please correct the error(s) below.</p>
		{% endif %}
		{% if formset.errors %}
			<p class="errornote">Wrong! Please correct the error(s) below.</p>
		{% endif %}

		<h4>앨범을 등록 하거나 수정합니다.</h4>

		<fieldset class="aligned">
			<div class="form-row">
				{{ form.name.label_tag }} {{ form.name }}
			</div>
			<div class="form-row">
				{{ form.description.label_tag }} {{ form.description }}
			</div>
		</fieldset>

		<h4>앨범에 사진을 등록 하거나 수정합니다.</h4>

		{{ formset.management_form }}
		{% for form in formset %}
			{{ form.id}}
		<fieldset class="aligned">
			<div class="form-row">
				{{ form.image.label_tag }} {{ form.image }}
			</div>
			<div class="form-row">
				{{ form.title.label_tag }} {{ form.title }}
			</div>
			<div class="form-row">
				{{ form.description.label_tag }} {{ form.description }}
			</div>
		</fieldset>
		{% endfor %}
		
		<div class="fl_right">	
			<div class="content-container" onclick="fn_submit();"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">제출</h3></fieldset></div> <!-- write -->	
		</div>

		<script type="text/javascript">document.getElementById('id_name').focus();</script>
	</form>
</div>
{% endblock %}

photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load static %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<script type="text/javascript">
	function fn_add(target){
		document.location.href= target + "/add";
	}

</script>
<div id ="content">
	<div class="fl_right">	
		<div class="content-container" style="position: relative;" onclick="fn_add('photo');"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">사진추가</h3></fieldset></div> <!-- write -->	
	</div>
    <div class="fl_right">	
		<div class="content-container" style="position: relative;" onclick="fn_add('album');"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">앨범추가</h3></fieldset></div> 
	</div>	
	<div class="gap10r"></div>
	{% for item in object_list %}

	<div class="clear_float">
		<h2 style="display:inline;"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h2>
		&emsp;
		<b><i>{{ item.description }}</i></b>
	</div>

	<hr/>

	<div class="album-list">
		{% for photo in item.photo_set.all|slice:":5" %} <!--print 5 thumbnail -->
		<div class="album-list-photo">
			<a href="{{ photo.get_absolute_url }}">
				<img class="thumbnail" src="{{ photo.image.thumb_url }}" />
			</a>
		</div>
		{% endfor %}
	</div>

	{% endfor %}	
	
</div>
{% endblock %}

photo/templates/photo/photo_change_list.html
{% extends "base.html" %}

{% block title %}photo_change_list.html{% endblock %}

{% block content %}
	<div id="content">
		<h1>사진 변경 - {{ user }}</h1>

		<table class="change-list">
			<tr>
				<th>Album</th>
				<th>Title</th>
				<th>Description</th>
				<th>Owner</th>
				<th>Update</th>
				<th>Delete</th>
			</tr>

			{% for item in object_list %}
			<tr>
				<td>{{ item.album}}</td>
				<td>{{ item.title}}</td>
				<td>{{ item.description}}</td>
				<td>{{ item.owner}}</td>
				<td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
				<td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
			</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}

photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}

{% block title %}photo_confirm_delete.html{% endblock %}

{% block content %}
	<div id="content">
		<h1>사진 삭제</h1>

		<form action="." id="submitrow" method="post">{% csrf_token %}
			<p>다음 사진을 정말 삭제하시겠습니까 - "{{ object }}" ? </p>
			<div class="fl_left">	
			<div class="content-container" onclick="fn_submit();"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">확인</h3></fieldset></div> <!-- write -->	
		</div>

		</form>
	</div>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}photo_detail.html{% endblock %}

{% load static %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<script type="text/javascript">
	function fn_move(todo, itemId){
		document.location.href="../" + itemId + "/" + todo;
	}

</script>
<div id ="content">

	<h2>{{ object.title}}</h2>

	<table class="photo-detail">
		<tr>
			<td>
				<a href="{{ object.image.url }}">
					<img style="max-width: 500px;" src="{{ object.image.url }}" />
				</a>
			</td>
			<td>
				<ul>
					<li>Photo Description</li>
					{% if object.description %}
						<p>{{ object.description|linebreaks }}</p>
					{% else %}
						<p>(blank)</p>
					{% endif %}
					<li>Date Uploaded</li>
						<p>{{ object.upload_date }}</p>
					<li>Album Name</li>
						<p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name}}</a></p>
				</ul>
			</td>
		</tr>
	</table>
	<hr style="margin: 5px 0;">
	<div class="fl_right">	
		<div class="content-container" style="position: relative;" onclick="fn_move('delete', {{object.id }});"><fieldset><h3 style="text-align:center;color:rgba(252,10,50,1);">삭제</h3></fieldset></div> 
	</div>
	<div class="fl_right">	
		<div class="content-container" style="position: relative;" onclick="fn_move('update', {{object.id }});"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">편집</h3></fieldset></div> 
	</div>

</div>
{% endblock %}

photo/templates/photo/photo_form.html
{% extends "base.html" %}

{% block title %}photo_form.html{% endblock %}

{% load static %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id ="content">
	<h1>사진 등록/수정 - {{ user }}</h1>

	{% if form.is_multipart %}
	<form enctype="multipart/form-data" id="submitrow" method="post" action=".">
	{% else %}
	<form method="post"	id="submitrow" action=".">
	{% endif %}
	{% csrf_token %}

		{% if form.errors %}
			<p class="errornote">Wrong! Please correct the error(s) below.</p>
		{% endif %}
		
		<h4>사진을 등록하거나 수정합니다.</h4>

		<fieldset class="aligned">
			<div class="form-row">
				{{ form.image.label_tag }} {{ form.image }}
			</div>
			<div class="form-row">
				{{ form.album.label_tag }} {{ form.album }}
				<button type="button"><a href="{% url 'photo:album_add' %}">Add Ablum</a></button>
			</div>
			<div class="form-row">
				{{ form.title.label_tag }} {{ form.title }}
			</div>
			<div class="form-row">
				{{ form.description.label_tag }} {{ form.description }}
			</div>
		</fieldset>
		
		
		<div class="fl_right">	
			<div class="content-container" onclick="fn_submit();"><fieldset><h3 style="text-align:center;color:rgba(252,217,36,1);">제출</h3></fieldset></div> <!-- write -->	
		</div>

		<script type="text/javascript">document.getElementById('id_album').focus();</script>
	</form>
</div>
{% endblock %}