blog/urls.py
from django.conf.urls import url,include
from blog.views import *

app_name = 'blog'

urlpatterns = [
	# Example : /
	url(r'^$', PostLV.as_view(), name = 'index'),

	# Example : /post/ (same as /)
	url(r'^post/$', PostLV.as_view(), name = 'post_list'),

	# Example : /post/django-example/
	url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name = 'post_detail'),

	# Example : /archive/
	url(r'^archive/$', PostAV.as_view(), name = 'post_archive'),

	# Example : /2012/
	url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name = 'post_year_archive'),

	# Example : /2012/nov/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name = 'post_month_archive'),

	# Example : /2012/nov/10/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name = 'post_day_archive'),

	# Example : /today/
	url(r'^today/$', PostTAV.as_view(), name = 'post_today_archive'),

	# Example: /tag/
	url(r'^tag/$', TagTV.as_view(), name = 'tag_cloud'),

	# Example: /tag/tagname/
	url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

	# Example: /search/
	url(r'^search/$', SearchFormView.as_view(), name='search'),

	#### add below for edit
	# Example: /add/
	url(r'^add/$', PostCreateView.as_view(), name="add"),

	# Example: /change/
	url(r'^change/$', PostChangeLV.as_view(), name="change"),

	# Example: /99/update/
	url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name="update"),

	# Example: /99/delete/
	url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name="delete"),

	url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor
]

myweb/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
#from home import views
from django.conf.urls.static import static  # add for photo
from django.conf import settings  # add for photo
from myweb.views import HomeView, HomeMobiView, UserCreateView, UserCreateDoneTV # for auth
import practice.views
#from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     # auth URL 3
#     url(r'^accounts/', include('django.contrib.auth.urls')),
#     url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
#     url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

#     url(r'^$', HomeView.as_view(), name='home'), 
#     url(r'^bookmark/', include('bookmark.urls', )),
#     url(r'^blog/', include('blog.urls', )),
# #    url(r'^$', views.index),
#     url(r'^photo/', include('photo.urls', )), # add for photo

#     # url(r'^rss/', include('rss.urls', )), # add for rss
# 	# Class-based view for bookmark app
# 	#url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
# 	#url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail')
#     url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor

#     # mobile
#     url(r'^m/', HomeMobiView.as_view(), name='mobihome'),

#     #practice
#     url(r'^practice/', include('practice.urls', )),

#     url(r'^bit.json$', HomeView.bitsise),    

    url(r'^admin/', admin.site.urls),
    # auth URL 3
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'), 
    path(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    path(r'^blog/', include('blog.urls', namespace='blog' )),
#    url(r'^$', views.index),
    path(r'^photo/', include('photo.urls', namespace='photo')), # add for photo

    # url(r'^rss/', include('rss.urls', )), # add for rss
    # Class-based view for bookmark app
    #url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
    #url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail')
    url(r'^ckeditor/', include('ckeditor_uploader.urls')), # ckeditor

    # mobile
    url(r'^m/', HomeMobiView.as_view(), name='mobihome'),

    #practice
    url(r'^practice/', include('practice.urls', )),

    url(r'^bit.json$', HomeView.bitsise), 
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # add for photo

photo/urls.py
from django.conf.urls import url
from photo.views import *

app_name = 'photo'

urlpatterns = [
	# Example : /
	url(r'^$', AlbumLV.as_view(), name = 'index'),

	# Example : /album/, same as /
	url(r'^album/$', AlbumLV.as_view(), name = 'album_list'),

	# Example : /album/99
	url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name = 'album_detail'),

	# Example : /photo/99
	url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name = 'photo_detail'),

	# Example : /album/add/
	url(r'^album/add/$' , AlbumPhotoCV.as_view(), name="album_add"),

	# Example : /album/change/
	url(r'^album/change/$' , AlbumChangeLV.as_view(), name="album_change"),

	# Example : /album/99/update/
	url(r'^album/(?P<pk>[0-9]+)/update/$' , AlbumPhotoUV.as_view(), name="album_update"),

	# Example : /album/99/delete/
	url(r'^album/(?P<pk>[0-9]+)/delete/$' , AlbumDeleteView.as_view(), name="album_delete"),

	# Example : /photo/add/
	url(r'^photo/add/$' , PhotoCreateView.as_view(), name="photo_add"),

	# Example : /photo/change/
	url(r'^photo/change/$' , PhotoChangeLV.as_view(), name="photo_change"),

	# Example : /photo/99/update/
	url(r'^photo/(?P<pk>[0-9]+)/update/$' , PhotoUpdateView.as_view(), name="photo_update"),

	# Example : /photo/99/delete/
	url(r'^photo/(?P<pk>[0-9]+)/delete/$' , PhotoDeleteView.as_view(), name="photo_delete"),


]

home/models.py
from django.db import models

# Create your models here.

class Stock(models.Model):
    pirce = 12345

    def get_price(self):
        return price

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
	return HttpResponse("running!")


templates/base.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %} Django Web Programming {% endblock %} </title>


{% load static %}

{% load static %}
<link rel="stylesheet" title="basecss" type="text/css" href="{% static 'css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>
<script type="text/javascript" src="https://code.highcharts.com/modules/exporting.js"></script>
<script type="text/javascript" src="https://code.highcharts.com/modules/data.js"></script>
<script type="text/javascript">
	if((/Mobi/.test(navigator.userAgent))) {
		$('head').append('<link rel="stylesheet" title="basecss_m" type="text/css" href="{% static 'css/base_m.css' %}" />');
		$('#maintitle').html("&nbsp;파이썬학습조직");
	}else{
		$('head').append('<link rel="stylesheet" title="basecss_m" type="text/css" href="{% static 'css/base.css' %}" />');
	}
</script>
<script type="text/javascript">
	function fn_write(){
		document.location.href = "add";

	}
	function fn_submit(){
		$('#submitrow').submit();
	}
</script>

</head>

<body>
	<div id="header">
		<a href="{% url 'home' %}" id="gohome" style="width: 220px;"><h2 class="maintitle" id="maintitle">파이썬학습조직-기술블로그</h2></a>
		<script type="text/javascript">
			if (/Mobi/.test(navigator.userAgent)) {
    		// mobile!
    			$('#gohome').attr("href","{% url 'mobihome' %}");
			}
		</script>
		
				
		{% if user.is_active %}
		<h4 class="welcome">환영합니다, 
			<strong>{% firstof user.get_short_name user.get_username %}</strong>
			<br />
			<a href="{% url 'password_change' %}">비밀번호 변경</a> / 
			<a href="{% url 'logout' %}">로그아웃</a>
		</h4>
		{% else %}
		<h4 class="welcome">방문을 환영합니다.
			<br />
			<a href="{% url 'login' %}">로그인</a> / 
			<a href="{% url 'register' %}">등록하기 </a>
		</h4>
		{% endif %}

		<!-- <div id="userarea">		
		{% if user.is_active %}
		<li>
			<h4 class="welcome">환영합니다, 
				<strong>{% firstof user.get_short_name user.get_username %}</strong>			
			</h4>
			<ul>
					<li><a href="{% url 'password_change' %}">PW 변경</a></li>
					<li><a href="{% url 'logout' %}">로그아웃</a></li>
			</ul>
		</li>
		{% else %}
		<h4 class="welcome">Welcome, Anonymous
			<a href="{% url 'login' %}">로그인</a> / 
			<a href="{% url 'register' %}">등록신청</a>
		</h4>
		{% endif %}
		</div> -->
		
	</div>

	<div id="menu">
		<li><a href="{% url 'bookmark:index' %}">즐겨찾기</a></li>
		<li><a href="{% url 'blog:index' %}">블로그</a></li>
		<li><a href="{% url 'photo:index' %}">앨범</a></li>

		<!-- <li><a href="#">Add &bigtriangledown;</a>
			<ul>
				<li><a href="{% url 'bookmark:add' %}">BookMark</a></li> 
				<li><a href="{% url 'blog:add' %}">Post</a></li>
				<li><a href="{% url 'photo:album_add' %}">Album</a></li> 
				<li><a href="{% url 'photo:photo_add' %}">Photo</a></li>
			</ul>
		</li>
		-->
		<!-- <li><a href="#">Change &bigtriangledown;</a>
			<ul>
				<li><a href="{% url 'bookmark:change' %}">BookMark</a></li>
				<li><a href="{% url 'blog:change' %}">Post</a></li>
				<li><a href="{% url 'photo:album_change' %}">Album</a></li>
				<li><a href="{% url 'photo:photo_change' %}">Photo</a></li>
			</ul>
		</li>  -->

		<!-- <li><a href="{% url 'blog:post_archive' %}">Archive</a></li> -->
		<!-- <li><a href="{% url 'blog:search' %}">Search</a></li> -->
		<li><a href="{% url 'admin:index' %}">관리자</a></li>
	</div>

	<!-- <div style="height: 20px;background:rgba(0,46,122,1); padding-left: 5px;width: 100%;"></div> -->

	{% block content %}{% endblock %}	
	{% block footer %}{% endblock %}
</body>

<script type="text/javascript">
    if((/Mobi/.test(navigator.userAgent))) $('#maintitle').html("&nbsp;&nbsp;파이썬학습조직");

</script>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}


{% load static  %}

{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{%block content %}
<div id="homeimg">
	<img src="{% static 'img/pycon2017.png' %}" style="align-content:center;width: 490px;height: 291px;" />
	<h4 >"Life is short, You need Python"</h4>
</div>
<script type="text/javascript">
	if (/Mobi/.test(navigator.userAgent)) {
    // mobile!
    	document.location.href="m/";
	}

	function getCoinVal(currency){
        $.get('/bit.json', {'coin' : currency}  ,function(jsondata) {
        		$('#'+ currency).html(jsondata);
        	});		        
	}

</script>
<div id="content_home">
	
	<hr style="margin: 5px 0;">

	<div class="blog-list">
		{% for post in posts %}
		<div class="cont_post">
			<h4><a href='{{ post.get_absolute_url }}' class="txt_wrap">{{post.title}} - {{post.modify_date|date:"N d, Y"}}</a></h4>
			<div class="cont_img">				
				<a href="{{ post.get_absolute_url }}"><img id="img{{ post.id }}" src="" style="width: 100%; height: auto;" /></a>
			</div>
			<div class="txt_shorten" id="{{ post.id }}">{{ post.content }}</div>	
		</div>		
		<script type="text/javascript">
			/**리스트에 img thumbnail 넣기 */
			var s =	$("#{{ post.id }}").html();			
			var e = document.createElement('div');
			e.innerHTML = s;
			var htm = e.childNodes[0].nodeValue;
			e.innerHTML = htm;
			var str = e.getElementsByTagName("img")[0];
			if( e.getElementsByTagName("img")[0] != "undefined" && e.getElementsByTagName("img")[0] != undefined ){
				var src = e.getElementsByTagName("img")[0].outerHTML;
				var tgt = document.getElementById("img{{ post.id }}");
				tgt.src = e.getElementsByTagName("img")[0].src;
				
			}			

			/**리스트에서 txt만 보이게 하기 */					
			var xxx = $(htm).text();
			$('#{{post.id}}').text(xxx);

		</script>
		{% endfor %}
		<div style="text-align: center;">
			<span>
			{% if page_obj.has_previous  %}
				<a href="?page={{ page_obj.previous_page_number }}">◀</a>
			{% endif  %}
			{% if page_obj.has_previous or page_obj.has_next  %}
			{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
			{% endif %}
			{% if page_obj.has_next  %}
				<a href="?page={{ page_obj.next_page_number }}">▶</a>
			{% endif   %}
			</span>
		</div>
	</div>
	<div class="tag-cloud">

		<div >
			<fieldset>
				<legend>SEARCH</legend>
				<form action="blog/search/" method="post"> {% csrf_token %}
					<input class="search_area" type="text" placeholder="학습조직 블로그 검색" name="search_word" value="" />
					<input class="btn_search"  type="submit" src="{% static 'img/magnifying-glass.png' %}" value=">>" />
				</form>
			</fieldset>
		</div>

		

		<div id="stock_cont">
		<h4><b>가상화폐</b></h4>
		BTC:&nbsp;<span style="color: #ff0000;" id="btc_krw"><script type="text/javascript">getCoinVal("btc_krw");</script></span><br />
		BCH:&nbsp;<span style="color: #ff0000;" id="bch_krw"><script type="text/javascript">getCoinVal("bch_krw");</script></span><br />
		XRP:&nbsp;<span style="color: #ff0000;" id="xrp_krw"><script type="text/javascript">getCoinVal("xrp_krw");</script></span>

		</div>

		<div class="gap40"></div>

		<h4><b>TAGS</b></h4>
		{% load tagging_tags %}
		{% tag_cloud_for_model blog.Post as tags with steps=6 min_count=1 distribution=log %}
		{% for tag in tags %}
		<span class="tag-{{tag.font_size}}">
			<a href="{% url 'blog:tagged_object_list' tag.name %}">&nbsp;{{tag.name}}&nbsp;</a>
		</span> 
		{% endfor %}
		
	</div>	

	
</div>	


{% endblock content %}
{% block footer %}
<div>
</div>
{% endblock footer %}


templates/test.html
{% load stock_filter %}
<span style="color: #ff0000;">한화 : {{ '000660.KS'|get_price }}</span>
			<div class="gap10"></div>
			<span style="color: #ff0000;">카카오 : {{ '035720.KS'|get_price }}</span>
			<span style="color: #ff0000;">삼성전자 : {{ '005930.KS'|get_price }}</span>
			<span style="color: #ff0000;">신라젠 : {{ '215600.KQ'|get_price }}</span>
			<span style="color: #ff0000;">LG전자 : {{ '066570.KS'|get_price }}</span>